[build]
builder = "nixpacks"

[build.nixpacksConfig]
installCmd = "cd frontend && npm install && npm run build && cd ../backend && npm install && cp -r ../frontend/dist ./public"

[deploy]
startCommand = "node server.production.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
